### ISSUE TITLE
nspawn.org cooperation <3

### ISSUE THREAD

**Issue by shibumi** [refi64/nsbox#11]
Hi,
I am the founder of https://nspawn.org, nspawn.org is planned as a little hub for systemd-nspawn images: https://nspawn.org/images/

I really like your project, do you think that we could work together at some way? I wrote a small proof of concept wrapper for nspawn.org called `nspawn`: https://github.com/nspawn/nspawn

The whole website and service is still pretty alpha

EDIT:

I tried to copy the vagrant command line a little bit. The images are build via `mkosi`.
The nspawn wrapper will initialize the gnupg keyring in `/etc/systemd/` and you can download images via:
`nspawn init <distribution>/<release>/<raw or tar>`
For example:
`nspawn init fedora/30/tar`

All images are signed and a checksum is provided as systemd-machined expects it. Supported are right now:
```
Fedora
Ubuntu
Arch Linux
Debian
```

**Comment by refi64** [comment]
What on earth, I never saw this issue 😅 Sorry for the super delayed reply...

nspawn.org definitely looks awesome, but honestly I'm not entirely sure how a collaboration would work. nsbox adds some required metadata and such on top of what systemd-nspawn natively wants, and I had it use OCI images as its format for interop purposes. I guess at this point you could see it more as a container tool built on nspawn rather than just an nspawn wrapper.
